language: minimal
dist: bionic
services: docker
env:
  - image=perl:5.30
before_install:
  - docker pull $image
  - docker run $image perl -V
script:
  - |
    docker run --init -it -v $PWD:/$TRAVIS_REPO_SLUG -w /$TRAVIS_REPO_SLUG $image bash -c '
    set -euxo pipefail
    curl -fsSL --compressed https://git.io/cpm | perl - install -g --with-develop --with-recommends
    prove -lr xt
    '
