language: perl
perl:
  - '5.8'
  - '5.10'
  - '5.16'
  - '5.30'
addons:
  apt:
    packages:
    - libdb-dev
install:
  - curl -fsSL --compressed https://git.io/cpm | perl - install -g --with-develop --with-recommends
script:
  - prove -lr --timer t xt
